// Catálogo de paletas curadas por psicologia das cores, pra apoiar identidade visual de
// personagens/cenários/marcas dentro do FoxAssets. Inspirado no formato do guia da Sansão Udemy
// (categorias como filtro, impacto/aplicação por paleta, copiar HEX), com paletas e textos
// autorais — não é cópia do conteúdo de lá.

export type Palette = {
  id: number;
  name: string;
  colors: string[];
  impact: string;
  application: string;
  tags: string[];
};

export const CATEGORIES = [
  "Vibrante", "Moderno", "Quente", "Luxuoso", "Minimalista",
  "Escuro", "Fresco", "Corporativo", "Suave", "Orgânico", "Pastel",
] as const;

export const PALETTES: Palette[] = [
  { id: 1, name: "Vitalidade Urbana", colors: ["#E2432F", "#F4A340", "#2E3440", "#DCD6CF"],
    impact: "Energia, juventude, movimento.",
    application: "Marcas esportivas, eventos de rua, startups de dinamismo acelerado.",
    tags: ["Vibrante", "Moderno", "Quente"] },
  { id: 2, name: "Elegância Noturna", colors: ["#211D1A", "#3A322B", "#B08D4F", "#D8D2C9"],
    impact: "Sofisticação, luxo, mistério.",
    application: "Joalherias, moda de gala, vinhos premium e marcas boutique de alto padrão.",
    tags: ["Luxuoso", "Minimalista", "Escuro"] },
  { id: 3, name: "Serenidade Marinha", colors: ["#1D6FA5", "#3BA9C4", "#7FD4DD", "#EAF7F8"],
    impact: "Calma, confiança, clareza lógica.",
    application: "Clínicas médicas, spas, tecnologia de dados e plataformas de bem-estar.",
    tags: ["Fresco", "Corporativo", "Suave"] },
  { id: 4, name: "Terra Orgânica", colors: ["#8A6A4C", "#B9926B", "#DDBB93", "#F1E4D3"],
    impact: "Natural, sustentável, aconchego familiar.",
    application: "Produtos ecológicos, alimentos orgânicos, cafés especiais e cosméticos naturais.",
    tags: ["Orgânico", "Quente", "Suave"] },
  { id: 5, name: "Neon Pulse", colors: ["#FF2E88", "#7B2FF7", "#00E5FF", "#0B0714"],
    impact: "Ousadia, adrenalina, cultura digital.",
    application: "Games, festivais de música eletrônica, apps de streaming e e-sports.",
    tags: ["Vibrante", "Moderno", "Escuro"] },
  { id: 6, name: "Cimento & Aço", colors: ["#2B2E33", "#565D66", "#8D96A0", "#E8EAED"],
    impact: "Precisão, solidez, racionalidade.",
    application: "Engenharia, construção civil, ferramentas B2B e software industrial.",
    tags: ["Moderno", "Corporativo", "Minimalista"] },
  { id: 7, name: "Pôr do Sol no Deserto", colors: ["#E85D3D", "#F2A65A", "#F6D186", "#7A4A3A"],
    impact: "Aconchego, nostalgia, calor humano.",
    application: "Turismo, gastronomia regional, marcas artesanais e cafeterias autorais.",
    tags: ["Quente", "Orgânico"] },
  { id: 8, name: "Jardim de Sálvia", colors: ["#5C7A5E", "#8FAE8B", "#C6DCC0", "#F3F6EE"],
    impact: "Equilíbrio, cuidado, respiro mental.",
    application: "Terapias holísticas, yoga, produtos de bem-estar e embalagens de farmácia natural.",
    tags: ["Suave", "Orgânico", "Fresco"] },
  { id: 9, name: "Confeitaria Pastel", colors: ["#F7C9D0", "#F9E2C5", "#CDE7DE", "#EDEBF5"],
    impact: "Delicadeza, ternura, leveza afetiva.",
    application: "Confeitarias, papelaria infantil, marcas de maternidade e presentes.",
    tags: ["Pastel", "Suave"] },
  { id: 10, name: "Sala de Reunião", colors: ["#0E2A47", "#1D4E89", "#5C7FA6", "#E6EBF2"],
    impact: "Confiabilidade, autoridade, estabilidade institucional.",
    application: "Bancos, seguradoras, consultorias e softwares corporativos.",
    tags: ["Corporativo", "Moderno", "Minimalista"] },
  { id: 11, name: "Champagne Real", colors: ["#1A1A1A", "#C9A860", "#E8DCC0", "#F7F3EA"],
    impact: "Exclusividade, requinte, tradição.",
    application: "Alta joalheria, hotéis cinco estrelas, perfumaria de nicho e eventos de gala.",
    tags: ["Luxuoso", "Escuro", "Minimalista"] },
  { id: 12, name: "Recife de Coral", colors: ["#FF6B6B", "#FFA26B", "#4ECDC4", "#1A535C"],
    impact: "Alegria, vitalidade tropical, acolhimento.",
    application: "Turismo de praia, apps de viagem, marcas de verão e bebidas refrescantes.",
    tags: ["Vibrante", "Quente", "Fresco"] },
  { id: 13, name: "Bosque ao Amanhecer", colors: ["#2F3E2E", "#4F6F52", "#A9C9A4", "#EDF3E7"],
    impact: "Renovação, tranquilidade, conexão com a natureza.",
    application: "Trilhas e ecoturismo, produtos florestais, marcas outdoor e sustentabilidade.",
    tags: ["Orgânico", "Fresco", "Suave"] },
  { id: 14, name: "Grafite & Lima", colors: ["#1C1C1E", "#3A3A3C", "#B4FF39", "#F2F2F2"],
    impact: "Disrupção, tecnologia, atitude jovem.",
    application: "Startups de tech, apps fitness, marcas de streetwear e gaming competitivo.",
    tags: ["Moderno", "Vibrante", "Escuro"] },
  { id: 15, name: "Algodão-Doce", colors: ["#FBD1E4", "#C9E4F6", "#FFF3B0", "#FDF6F0"],
    impact: "Fantasia, doçura, memória de infância.",
    application: "Marcas infantis, doceria artesanal, papelaria criativa e brinquedos.",
    tags: ["Pastel", "Suave", "Vibrante"] },
  { id: 16, name: "Vinho & Couro", colors: ["#3B0F14", "#6E1E2B", "#A9825F", "#EDE2D3"],
    impact: "Intensidade, tradição, maturidade sensorial.",
    application: "Adegas, restaurantes de carnes, marcas de couro e barbearias premium.",
    tags: ["Luxuoso", "Quente", "Escuro"] },
  { id: 17, name: "Névoa Escandinava", colors: ["#D7DEE3", "#AEB9C2", "#5F6B75", "#2C333A"],
    impact: "Sobriedade, clareza, funcionalidade silenciosa.",
    application: "Design de interiores, arquitetura, marcas de moda minimalista.",
    tags: ["Minimalista", "Fresco", "Corporativo"] },
  { id: 18, name: "Citrus Splash", colors: ["#FF9F1C", "#FFBF69", "#2EC4B6", "#011627"],
    impact: "Energia positiva, frescor, otimismo.",
    application: "Bebidas cítricas, academias, apps de produtividade e marcas jovens.",
    tags: ["Vibrante", "Fresco", "Moderno"] },
  { id: 19, name: "Areia & Sal", colors: ["#E8DCC8", "#D9C29B", "#8C9A93", "#3E4B48"],
    impact: "Autenticidade, simplicidade, vida costeira.",
    application: "Moda praia, pousadas, marcas de home decor e produtos artesanais.",
    tags: ["Orgânico", "Minimalista", "Suave"] },
  { id: 20, name: "Ametista Digital", colors: ["#1A0B2E", "#4E2A84", "#8E5CDB", "#D9C6F5"],
    impact: "Inovação, criatividade, futuro tecnológico.",
    application: "SaaS de IA, apps criativos, marcas de web3 e portfólios de design.",
    tags: ["Moderno", "Escuro", "Vibrante"] },
  { id: 21, name: "Lavanda Suave", colors: ["#E6D9F2", "#C9B6E4", "#9E8FBF", "#F5F1FA"],
    impact: "Serenidade, introspecção, cuidado emocional.",
    application: "Apps de meditação, saúde mental, cosméticos delicados e papelaria.",
    tags: ["Suave", "Pastel", "Fresco"] },
  { id: 22, name: "Ônix Executivo", colors: ["#0B0B0D", "#232326", "#4A4A4E", "#C9CACC"],
    impact: "Poder discreto, precisão, controle.",
    application: "Consultorias de alto nível, fintechs, automóveis premium e software enterprise.",
    tags: ["Corporativo", "Escuro", "Minimalista"] },
  { id: 23, name: "Manga & Coco", colors: ["#FFB627", "#FF7F11", "#F2F0E4", "#5C4033"],
    impact: "Apetite, hospitalidade, calor tropical.",
    application: "Food trucks, sorveterias artesanais, marcas de suco natural e restaurantes casuais.",
    tags: ["Quente", "Vibrante", "Orgânico"] },
  { id: 24, name: "Glacial", colors: ["#CFE8F3", "#8FC1DC", "#4A7A96", "#12222E"],
    impact: "Precisão fria, tecnologia, foco.",
    application: "Softwares de análise de dados, marcas de equipamento outdoor e telecom.",
    tags: ["Fresco", "Corporativo", "Moderno"] },
  { id: 25, name: "Musgo Profundo", colors: ["#1B2E1F", "#33532E", "#6B8F5A", "#D6E3C8"],
    impact: "Estabilidade natural, crescimento, resiliência.",
    application: "Marcas de outdoor, suplementos naturais, cervejarias artesanais.",
    tags: ["Orgânico", "Escuro", "Suave"] },
  { id: 26, name: "Rosê Contemporâneo", colors: ["#E8B4B8", "#D89A9E", "#F6E6D8", "#2B2523"],
    impact: "Sofisticação acessível, feminilidade moderna.",
    application: "Beleza e skincare, moda contemporânea, hotelaria boutique.",
    tags: ["Pastel", "Moderno", "Luxuoso"] },
  { id: 27, name: "Concreto Vivo", colors: ["#DAD7D2", "#B7B2AA", "#6F6A63", "#E24A31"],
    impact: "Autenticidade urbana com um toque de ousadia.",
    application: "Marcas de arquitetura, estúdios criativos, cafés de bairro e coworkings.",
    tags: ["Minimalista", "Moderno", "Quente"] },
  { id: 28, name: "Safira Corporativa", colors: ["#0A2A5E", "#1E4E8C", "#4E7FB0", "#DCE6F0"],
    impact: "Confiança institucional, competência, segurança.",
    application: "Bancos digitais, seguros, softwares de gestão e educação corporativa.",
    tags: ["Corporativo", "Fresco", "Moderno"] },
  { id: 29, name: "Terracota Artesanal", colors: ["#C1502E", "#D97F4B", "#E8C39E", "#4A3728"],
    impact: "Calor humano, tradição, feito à mão.",
    application: "Cerâmica, marcas de artesanato, cafés de especialidade e moda autoral.",
    tags: ["Quente", "Orgânico", "Suave"] },
  { id: 30, name: "Ardósia Minimal", colors: ["#EDEEF0", "#C7CACD", "#71767C", "#2A2D31"],
    impact: "Clareza, ordem, foco no essencial.",
    application: "Portfólios, apps de produtividade, arquitetura e design gráfico.",
    tags: ["Minimalista", "Corporativo", "Fresco"] },
  { id: 31, name: "Framboesa Elétrica", colors: ["#C9184A", "#FF4D6D", "#FFB3C1", "#590D22"],
    impact: "Paixão, ousadia, apetite visual imediato.",
    application: "Moda jovem, cosméticos vibrantes, marcas de streetwear feminino.",
    tags: ["Vibrante", "Quente"] },
  { id: 32, name: "Aço Escovado", colors: ["#3D4045", "#6C7075", "#A6A9AD", "#F1F1F2"],
    impact: "Robustez, engenharia, confiabilidade técnica.",
    application: "Ferramentas industriais, automotivo, equipamentos profissionais.",
    tags: ["Corporativo", "Minimalista", "Escuro"] },
  { id: 33, name: "Jade Imperial", colors: ["#0B3D2E", "#1F6E4E", "#5FAE87", "#D4E9DD"],
    impact: "Prosperidade, tradição oriental, crescimento.",
    application: "Chás premium, spas orientais, marcas de bem-estar financeiro.",
    tags: ["Luxuoso", "Orgânico", "Escuro"] },
  { id: 34, name: "Amanhecer Rosado", colors: ["#FFCAD4", "#F4989C", "#FFE5D9", "#B5838D"],
    impact: "Ternura, romance, começo suave.",
    application: "Marcas de maternidade, floriculturas, papelaria de casamento.",
    tags: ["Pastel", "Suave"] },
  { id: 35, name: "Base de Dados", colors: ["#0D1B2A", "#1B263B", "#415A77", "#E0E1DD"],
    impact: "Confiabilidade técnica, profundidade, seriedade.",
    application: "Softwares de infraestrutura, cibersegurança, cloud computing.",
    tags: ["Corporativo", "Escuro", "Moderno"] },
  { id: 36, name: "Pomar de Pêssego", colors: ["#FFB4A2", "#FFCDB2", "#E5989B", "#6D6875"],
    impact: "Doçura madura, conforto, feminilidade suave.",
    application: "Cosméticos, moda íntima, marcas de autocuidado.",
    tags: ["Pastel", "Suave", "Quente"] },
  { id: 37, name: "Obsidiana Vermelha", colors: ["#0A0A0A", "#8B0000", "#B22222", "#2B2B2B"],
    impact: "Intensidade, perigo controlado, poder.",
    application: "Games de ação, marcas automotivas de performance, energéticos.",
    tags: ["Escuro", "Vibrante", "Luxuoso"] },
  { id: 38, name: "Horizonte Nórdico", colors: ["#E8EEF1", "#B8CBD6", "#6E8CA0", "#243B4A"],
    impact: "Frieza elegante, clareza escandinava.",
    application: "Design de móveis, arquitetura de interiores, marcas de conforto térmico.",
    tags: ["Fresco", "Minimalista", "Corporativo"] },
  { id: 39, name: "Café com Canela", colors: ["#4A2C2A", "#7B4B36", "#C08552", "#EAD7C3"],
    impact: "Aconchego, tradição, ritual diário.",
    application: "Cafeterias, padarias artesanais, marcas de casa e ritual matinal.",
    tags: ["Quente", "Orgânico", "Suave"] },
  { id: 40, name: "Safira Neon", colors: ["#0F4C81", "#3A86FF", "#8ECAE6", "#001220"],
    impact: "Confiança tecnológica com toque futurista.",
    application: "Fintechs, apps de investimento, plataformas de dados em tempo real.",
    tags: ["Moderno", "Fresco", "Corporativo"] },
  { id: 41, name: "Flor de Cerejeira", colors: ["#FFD9E8", "#F7A8C4", "#FFF0F5", "#4A3F41"],
    impact: "Delicadeza sazonal, beleza efêmera.",
    application: "Marcas de beleza asiática, papelaria fina, eventos primaveris.",
    tags: ["Pastel", "Suave", "Luxuoso"] },
  { id: 42, name: "Selva Tropical", colors: ["#0B4619", "#1C7C3E", "#7FB069", "#F4E285"],
    impact: "Exuberância, vida, energia natural.",
    application: "Turismo ecológico, marcas de suco natural, produtos veganos.",
    tags: ["Orgânico", "Vibrante", "Quente"] },
  { id: 43, name: "Chumbo & Ouro", colors: ["#1B1B1E", "#3A3A3F", "#D4AF37", "#F5EFE0"],
    impact: "Poder discreto com toque de exclusividade.",
    application: "Alfaiataria, escritórios de advocacia premium, clubes privados.",
    tags: ["Luxuoso", "Escuro", "Corporativo"] },
  { id: 44, name: "Menta Refrescante", colors: ["#D4F5E9", "#8FE3C0", "#3FA796", "#0D3B2E"],
    impact: "Frescor, higiene, revitalização.",
    application: "Produtos de higiene bucal, farmácias, academias e bebidas funcionais.",
    tags: ["Fresco", "Suave", "Vibrante"] },
  { id: 45, name: "Terra de Marte", colors: ["#7A3B2E", "#B5563C", "#D9855B", "#F2D9C4"],
    impact: "Aventura, exploração, aspereza quente.",
    application: "Marcas outdoor, equipamentos de trilha, games de sobrevivência.",
    tags: ["Quente", "Orgânico", "Moderno"] },
  { id: 46, name: "Vidro Fumê", colors: ["#2A2A2E", "#4E4E55", "#7A7A82", "#D8D8DB"],
    impact: "Discrição sofisticada, modernidade urbana.",
    application: "Arquitetura contemporânea, moda unissex, estúdios de design.",
    tags: ["Minimalista", "Moderno", "Escuro"] },
  { id: 47, name: "Girassol de Verão", colors: ["#FFC93C", "#FFB100", "#FFF4D6", "#4A3F35"],
    impact: "Otimismo, calor solar, positividade.",
    application: "Marcas de verão, sorveterias, festivais ao ar livre.",
    tags: ["Vibrante", "Quente", "Pastel"] },
  { id: 48, name: "Ferro Fundido", colors: ["#1A1A1A", "#3D3D3D", "#8A5A44", "#C9A87C"],
    impact: "Robustez artesanal, tradição industrial.",
    application: "Marcas de ferramentas, cervejarias artesanais, marcenaria.",
    tags: ["Escuro", "Quente", "Corporativo"] },
  { id: 49, name: "Céu de Verão", colors: ["#87CEEB", "#B0E0E6", "#FFFACD", "#1B3A4B"],
    impact: "Leveza, liberdade, dias claros.",
    application: "Turismo, marcas infantis, apps de clima e viagem.",
    tags: ["Fresco", "Pastel", "Vibrante"] },
  { id: 50, name: "Borgonha Profundo", colors: ["#4A0E1F", "#7A1F3D", "#B3446C", "#EED9DF"],
    impact: "Paixão madura, elegância intensa.",
    application: "Vinícolas, moda de inverno, marcas de perfumaria intensa.",
    tags: ["Luxuoso", "Escuro", "Quente"] },
  { id: 51, name: "Grafite Suave", colors: ["#E4E4E7", "#B8B8BE", "#6B6B72", "#39393E"],
    impact: "Neutralidade elegante, versatilidade.",
    application: "Identidade visual corporativa, apps utilitários, moda unissex.",
    tags: ["Minimalista", "Corporativo", "Suave"] },
  { id: 52, name: "Coral Vivo", colors: ["#FF6F59", "#FFA69E", "#FAF3DD", "#2B2D42"],
    impact: "Vitalidade, acolhimento caloroso.",
    application: "Restaurantes casuais, marcas de moda praia, apps de social.",
    tags: ["Vibrante", "Quente", "Suave"] },
  { id: 53, name: "Névoa Violeta", colors: ["#D8CFE8", "#B39DDB", "#7E57C2", "#2E1F47"],
    impact: "Mistério suave, criatividade introspectiva.",
    application: "Marcas de tarot e astrologia, apps de bem-estar, moda alternativa.",
    tags: ["Suave", "Escuro", "Moderno"] },
  { id: 54, name: "Trigo Dourado", colors: ["#E8C872", "#F1E0A8", "#8C6D3F", "#FAF6EC"],
    impact: "Fartura, tradição rural, simplicidade honesta.",
    application: "Padarias, produtos de grãos e cereais, marcas agrícolas.",
    tags: ["Quente", "Orgânico", "Suave"] },
  { id: 55, name: "Sinal de Néon", colors: ["#FF006E", "#FB5607", "#FFBE0B", "#0B0B10"],
    impact: "Impacto imediato, cultura pop, ousadia.",
    application: "Bares e vida noturna, marcas de streetwear, eventos e festivais.",
    tags: ["Vibrante", "Escuro", "Moderno"] },
  { id: 56, name: "Pedra Calcária", colors: ["#EDE8E0", "#D3C9B8", "#A69C87", "#5A5348"],
    impact: "Solidez atemporal, simplicidade rústica.",
    application: "Arquitetura, marcas de construção sustentável, home decor.",
    tags: ["Minimalista", "Orgânico", "Corporativo"] },
  { id: 57, name: "Azul Meia-Noite Corporativo", colors: ["#03071E", "#023E8A", "#0077B6", "#CAF0F8"],
    impact: "Autoridade calma, visão de longo prazo.",
    application: "Seguradoras, consultorias estratégicas, universidades e educação.",
    tags: ["Corporativo", "Escuro", "Fresco"] },
  { id: 58, name: "Damasco Suave", colors: ["#F6C39A", "#F2A65A", "#FCE4D8", "#6B4226"],
    impact: "Calor acolhedor, generosidade.",
    application: "Marcas de culinária caseira, produtos de padaria, hospitalidade.",
    tags: ["Quente", "Suave", "Orgânico"] },
  { id: 59, name: "Prata Futurista", colors: ["#C0C0C0", "#E5E5E5", "#3D5A80", "#0A0A0A"],
    impact: "Precisão tecnológica, minimalismo funcional.",
    application: "Eletrônicos, wearables, marcas de inovação e ciência.",
    tags: ["Moderno", "Minimalista", "Escuro"] },
  { id: 60, name: "Jardim Botânico", colors: ["#2D5A27", "#68A357", "#A8D5BA", "#F4F9F4"],
    impact: "Vitalidade natural, cuidado ambiental.",
    application: "Viveiros e jardinagem, marcas de skincare natural, ecoturismo.",
    tags: ["Orgânico", "Fresco", "Vibrante"] },
  { id: 61, name: "Púrpura Real", colors: ["#3C1053", "#6A0DAD", "#B185DB", "#EFE6F7"],
    impact: "Realeza, criatividade, ambição.",
    application: "Marcas de entretenimento premium, jogos de fantasia, cosméticos de luxo.",
    tags: ["Luxuoso", "Vibrante", "Moderno"] },
  { id: 62, name: "Areia do Saara", colors: ["#EDD9B0", "#D9B979", "#B08654", "#5C4630"],
    impact: "Calor seco, resistência, jornada.",
    application: "Marcas de viagem e aventura, moda utilitária, cosméticos masculinos.",
    tags: ["Quente", "Orgânico", "Minimalista"] },
  { id: 63, name: "Água-Marinha Executiva", colors: ["#004E64", "#00A5CF", "#9FFFCB", "#25274D"],
    impact: "Clareza profissional com frescor moderno.",
    application: "Consultorias de tecnologia, healthtechs, apps financeiros.",
    tags: ["Corporativo", "Fresco", "Moderno"] },
  { id: 64, name: "Cereja Doce", colors: ["#D62828", "#F77F00", "#FCBF49", "#EAE2B7"],
    impact: "Apetite, festividade, calor convidativo.",
    application: "Marcas de fast-food gourmet, doceria, bebidas festivas.",
    tags: ["Quente", "Vibrante"] },
  { id: 65, name: "Cinza Urbano", colors: ["#F5F5F5", "#D9D9D9", "#8C8C8C", "#262626"],
    impact: "Neutralidade moderna, foco no conteúdo.",
    application: "Apps de produtividade, portfólios fotográficos, editoriais.",
    tags: ["Minimalista", "Moderno", "Corporativo"] },
  { id: 66, name: "Orquídea Noturna", colors: ["#2E1A47", "#5E3B76", "#B185A7", "#F1E4F3"],
    impact: "Sensualidade discreta, elegância exótica.",
    application: "Perfumaria, moda íntima, spas de alto padrão.",
    tags: ["Luxuoso", "Escuro", "Suave"] },
  { id: 67, name: "Limão Siciliano", colors: ["#FFF275", "#FFE066", "#D4E09B", "#38601B"],
    impact: "Frescor cítrico, energia limpa.",
    application: "Bebidas naturais, produtos de limpeza, marcas de verão.",
    tags: ["Vibrante", "Fresco", "Orgânico"] },
  { id: 68, name: "Bronze Antigo", colors: ["#8C6239", "#B08968", "#DDB892", "#3C2A21"],
    impact: "Tradição histórica, artesania duradoura.",
    application: "Museus, marcas de relojoaria, produtos de couro envelhecido.",
    tags: ["Luxuoso", "Quente", "Escuro"] },
  { id: 69, name: "Céu Polar", colors: ["#EAF4FC", "#C7E4F5", "#7FB3D5", "#1B4965"],
    impact: "Pureza fria, amplitude, respiro.",
    application: "Marcas farmacêuticas, purificadores de ar, telecomunicações.",
    tags: ["Fresco", "Minimalista", "Corporativo"] },
  { id: 70, name: "Salmão Contemporâneo", colors: ["#FA9F85", "#FFCAB1", "#FFEDE1", "#5C4B51"],
    impact: "Calor moderno, acessibilidade elegante.",
    application: "Marcas de wellness, apps de lifestyle, moda casual premium.",
    tags: ["Pastel", "Moderno", "Suave"] },
  { id: 71, name: "Verde Bandeira", colors: ["#013220", "#0B6E4F", "#08A045", "#6BCB77"],
    impact: "Crescimento robusto, confiança financeira.",
    application: "Bancos verdes, fintechs de investimento, marcas de sustentabilidade corporativa.",
    tags: ["Corporativo", "Vibrante", "Orgânico"] },
  { id: 72, name: "Chocolate Amargo", colors: ["#3E2723", "#6D4C41", "#A1887F", "#EFEBE9"],
    impact: "Riqueza sensorial, indulgência sofisticada.",
    application: "Chocolaterias premium, cafeterias de especialidade, marcas gourmet.",
    tags: ["Luxuoso", "Quente", "Escuro"] },
  { id: 73, name: "Turquesa Caribenha", colors: ["#00B4B4", "#3FDBDB", "#B2F5F5", "#023436"],
    impact: "Frescor exótico, escapismo tropical.",
    application: "Resorts, marcas de turismo de luxo, bebidas tropicais.",
    tags: ["Fresco", "Vibrante", "Luxuoso"] },
  { id: 74, name: "Papel Reciclado", colors: ["#EDE6DB", "#D6C9B5", "#A79A82", "#4A4335"],
    impact: "Autenticidade sustentável, simplicidade honesta.",
    application: "Marcas eco-friendly, papelaria artesanal, embalagens conscientes.",
    tags: ["Orgânico", "Minimalista", "Suave"] },
  { id: 75, name: "Magenta Digital", colors: ["#D90368", "#F72585", "#B5179E", "#0A0014"],
    impact: "Ousadia digital, presença de marca forte.",
    application: "Apps sociais, marcas de moda disruptiva, festivais criativos.",
    tags: ["Vibrante", "Moderno", "Escuro"] },
  { id: 76, name: "Oliva Mediterrânea", colors: ["#6B7A3A", "#A3B565", "#D8DFC6", "#3E4222"],
    impact: "Simplicidade natural, tradição mediterrânea.",
    application: "Azeites e alimentos gourmet, marcas de bem-estar, moda linho.",
    tags: ["Orgânico", "Suave", "Quente"] },
  { id: 77, name: "Cobalto Institucional", colors: ["#001845", "#0353A4", "#0466C8", "#B6CCFE"],
    impact: "Confiança absoluta, autoridade técnica.",
    application: "Governo digital, saúde pública, seguradoras de grande porte.",
    tags: ["Corporativo", "Fresco", "Escuro"] },
  { id: 78, name: "Rosa Chá", colors: ["#F2D7D9", "#D8A7B1", "#B38B94", "#4A3B3D"],
    impact: "Feminilidade discreta, nostalgia elegante.",
    application: "Moda vintage, chás e confeitaria fina, papelaria de casamento.",
    tags: ["Pastel", "Suave", "Luxuoso"] },
  { id: 79, name: "Vulcânico", colors: ["#1A1A1A", "#4A1C1C", "#C1440E", "#F26B0F"],
    impact: "Força bruta, transformação intensa.",
    application: "Marcas de fitness extremo, energéticos, games de ação.",
    tags: ["Escuro", "Vibrante", "Quente"] },
  { id: 80, name: "Branco Ártico", colors: ["#FFFFFF", "#F0F4F8", "#D9E2EC", "#334E68"],
    impact: "Pureza clínica, minimalismo absoluto.",
    application: "Marcas de saúde, tecnologia médica, produtos premium de limpeza.",
    tags: ["Minimalista", "Fresco", "Corporativo"] },
  { id: 81, name: "Tangerina Pop", colors: ["#FF7B00", "#FF9E00", "#FFD500", "#3A0CA3"],
    impact: "Energia lúdica, diversão instantânea.",
    application: "Marcas infantis, apps de entretenimento, embalagens de snacks.",
    tags: ["Vibrante", "Quente", "Moderno"] },
  { id: 82, name: "Granito Polido", colors: ["#D6D6D6", "#A0A0A0", "#5C5C5C", "#1E1E1E"],
    impact: "Solidez atemporal, precisão arquitetônica.",
    application: "Escritórios de arquitetura, imobiliárias de alto padrão, design industrial.",
    tags: ["Minimalista", "Corporativo", "Escuro"] },
  { id: 83, name: "Hortelã & Limão", colors: ["#A8E6CF", "#DCEDC1", "#FFD3B6", "#1B4332"],
    impact: "Leveza refrescante, equilíbrio saudável.",
    application: "Marcas de alimentação saudável, academias, bebidas funcionais.",
    tags: ["Fresco", "Pastel", "Vibrante"] },
  { id: 84, name: "Couro Envelhecido", colors: ["#5C3D2E", "#8B5E3C", "#C68B59", "#E8D5B7"],
    impact: "Masculinidade clássica, durabilidade.",
    application: "Barbearias, marcas de acessórios de couro, uísques premium.",
    tags: ["Luxuoso", "Quente", "Escuro"] },
  { id: 85, name: "Céu de Anoitecer", colors: ["#2C0735", "#620080", "#A100FF", "#FF6EC7"],
    impact: "Fantasia noturna, criatividade vibrante.",
    application: "Marcas de entretenimento, festivais de música, apps de streaming.",
    tags: ["Vibrante", "Escuro", "Moderno"] },
  { id: 86, name: "Linho Natural", colors: ["#F5F0E6", "#E3D8C3", "#BCA88D", "#6B5B4A"],
    impact: "Simplicidade têxtil, conforto neutro.",
    application: "Moda slow fashion, home decor, marcas de bem-estar doméstico.",
    tags: ["Orgânico", "Minimalista", "Suave"] },
  { id: 87, name: "Esmeralda Corporativa", colors: ["#014D4E", "#02605F", "#04A777", "#D4F1F4"],
    impact: "Crescimento confiável, estabilidade verde.",
    application: "Bancos sustentáveis, healthtechs, consultorias ambientais.",
    tags: ["Corporativo", "Fresco", "Luxuoso"] },
  { id: 88, name: "Framboesa & Creme", colors: ["#E63946", "#F1FAEE", "#FFB4A2", "#457B9D"],
    impact: "Doçura contrastante, apetite visual.",
    application: "Confeitarias gourmet, embalagens de sobremesas, marcas de padaria fina.",
    tags: ["Pastel", "Vibrante", "Suave"] },
  { id: 89, name: "Antracite Técnico", colors: ["#161A1D", "#31393C", "#5C6970", "#B8C4CA"],
    impact: "Precisão técnica, seriedade industrial.",
    application: "Softwares de engenharia, marcas de equipamentos técnicos, B2B pesado.",
    tags: ["Corporativo", "Escuro", "Minimalista"] },
  { id: 90, name: "Pêssego ao Amanhecer", colors: ["#FFE5D4", "#FFCBA4", "#FFA69E", "#8A5A44"],
    impact: "Calor suave, começo gentil.",
    application: "Marcas de café da manhã, produtos de bebê, papelaria delicada.",
    tags: ["Pastel", "Quente", "Suave"] },
  { id: 91, name: "Índigo Profundo", colors: ["#0B132B", "#1C2541", "#3A506B", "#5BC0BE"],
    impact: "Introspecção, sabedoria, profundidade calma.",
    application: "Apps de leitura, marcas editoriais, plataformas de aprendizado.",
    tags: ["Escuro", "Corporativo", "Fresco"] },
  { id: 92, name: "Kiwi Tropical", colors: ["#8AB833", "#C3E88D", "#F2F7E9", "#3C4A1E"],
    impact: "Frescor exótico, vitalidade natural.",
    application: "Sucos e smoothies, marcas veganas, produtos de nutrição esportiva.",
    tags: ["Vibrante", "Orgânico", "Fresco"] },
  { id: 93, name: "Cinza Pérola", colors: ["#EAE6E1", "#CFC9C0", "#A69F94", "#3D3833"],
    impact: "Sofisticação neutra, versatilidade atemporal.",
    application: "Moda de luxo minimalista, joalherias contemporâneas, hotelaria boutique.",
    tags: ["Minimalista", "Luxuoso", "Suave"] },
  { id: 94, name: "Sangria de Verão", colors: ["#7A1F2B", "#C13E4C", "#F2A9A1", "#FCE4DE"],
    impact: "Sensualidade quente, festividade adulta.",
    application: "Vinícolas e bebidas alcoólicas, restaurantes mediterrâneos, eventos de verão.",
    tags: ["Quente", "Vibrante", "Luxuoso"] },
  { id: 95, name: "Névoa da Manhã", colors: ["#E8ECEF", "#C9D2D8", "#8FA0AB", "#3D4C55"],
    impact: "Calma matinal, clareza suave.",
    application: "Apps de meditação, marcas de chá, produtos de sono.",
    tags: ["Fresco", "Suave", "Minimalista"] },
  { id: 96, name: "Ouro Rosa", colors: ["#E8C4C4", "#D9A8A0", "#C9967D", "#F5E6E0"],
    impact: "Elegância contemporânea, luxo acessível.",
    application: "Tecnologia premium, joias delicadas, cosméticos de alto padrão.",
    tags: ["Luxuoso", "Pastel", "Moderno"] },
  { id: 97, name: "Bambu Zen", colors: ["#7A8B5A", "#A9BA82", "#D6E0BE", "#40492F"],
    impact: "Equilíbrio oriental, crescimento silencioso.",
    application: "Estúdios de yoga, marcas de decoração zen, produtos de meditação.",
    tags: ["Orgânico", "Suave", "Minimalista"] },
  { id: 98, name: "Vermelho Laca", colors: ["#A4133C", "#C9184A", "#800F2F", "#FFCCD5"],
    impact: "Intensidade cerimonial, prestígio cultural.",
    application: "Marcas de luxo asiático, restaurantes de alta gastronomia, eventos formais.",
    tags: ["Luxuoso", "Vibrante", "Escuro"] },
  { id: 99, name: "Azul Piscina", colors: ["#CAF0F8", "#90E0EF", "#00B4D8", "#03045E"],
    impact: "Diversão refrescante, verão despreocupado.",
    application: "Resorts, marcas de moda praia, apps de lazer e turismo.",
    tags: ["Fresco", "Vibrante", "Moderno"] },
  { id: 100, name: "Platina Absoluta", colors: ["#F7F7F8", "#E1E1E4", "#B0B0B6", "#232326"],
    impact: "Excelência silenciosa, luxo definitivo.",
    application: "Marcas de altíssimo padrão, private banking, alta relojoaria.",
    tags: ["Luxuoso", "Minimalista", "Corporativo"] },
];
