<?php

namespace Database\Seeders;

use App\Models\GenModel;
use Illuminate\Database\Seeder;

/**
 * Catálogo KIE.ai — todos os modelos do agregador, organizados por `kind`
 * (video/image/audio/text). Gerado do market real da KIE (playground/pagePlaygroundGroup, 79 grupos).
 *
 * Secure-by-default: tudo entra is_active=FALSE e cost_credits=NULL.
 * O operador, no Filament, define o preço em créditos + nome white-label e SÓ ENTÃO ativa.
 * provider_model_id = path do market da KIE (referência; o `model` exato por variante
 * é resolvido na integração do engine via createTask).
 */
class KieModelsSeeder extends Seeder
{
    public function run(): void
    {
        $models = [
            ['slug' => 'kie-seedance-2-5', 'display_name' => 'Seedance 2.5', 'kind' => 'video', 'provider_model_id' => 'seedance-2-5', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video', 'Video to Video'], 'variants' => 0, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 0],
            ['slug' => 'kie-seedance-2-0-mini', 'display_name' => 'Seedance 2.0 Mini', 'kind' => 'video', 'provider_model_id' => 'seedance-2-0-mini', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video', 'Video to Video'], 'variants' => 1, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 1],
            ['slug' => 'kie-happyhorse-1-1', 'display_name' => 'HappyHorse-1.1', 'kind' => 'video', 'provider_model_id' => 'happyhorse-1-1', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 3, 'upstream' => 'Alibaba'], 'is_active' => false, 'sort_order' => 2],
            ['slug' => 'kie-gpt-5-6', 'display_name' => 'GPT-5.6', 'kind' => 'text', 'provider_model_id' => 'gpt-5-6', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 0, 'upstream' => 'OpenAI'], 'is_active' => false, 'sort_order' => 3],
            ['slug' => 'kie-kling-3-0-turbo', 'display_name' => 'Kling 3.0 Turbo', 'kind' => 'video', 'provider_model_id' => 'kling-3-0-turbo', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 2, 'upstream' => 'Kling'], 'is_active' => false, 'sort_order' => 4],
            ['slug' => 'kie-volcengine-video-to-video-lip-sync', 'display_name' => 'Volcengine Video-to-Video Lip Sync', 'kind' => 'video', 'provider_model_id' => 'volcengine-video-to-video-lip-sync', 'capabilities' => ['task_types' => ['Lip Sync'], 'variants' => 1, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 5],
            ['slug' => 'kie-omnihuman-1-5', 'display_name' => 'OmniHuman 1.5', 'kind' => 'video', 'provider_model_id' => 'omnihuman-1-5', 'capabilities' => ['task_types' => ['Lip Sync'], 'variants' => 3, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 6],
            ['slug' => 'kie-claude-fable-5', 'display_name' => 'Claude Fable 5', 'kind' => 'text', 'provider_model_id' => 'claude-fable-5', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'Anthropic'], 'is_active' => false, 'sort_order' => 7],
            ['slug' => 'kie-grok-imagine-video-1-5', 'display_name' => 'Grok Imagine Video 1.5', 'kind' => 'video', 'provider_model_id' => 'grok-imagine-video-1.5', 'capabilities' => ['task_types' => ['Image to Video'], 'variants' => 1, 'upstream' => 'Grok'], 'is_active' => false, 'sort_order' => 8],
            ['slug' => 'kie-claude-opus-4-8', 'display_name' => 'Claude Opus 4.8', 'kind' => 'text', 'provider_model_id' => 'claude-opus-4-8', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'Anthropic'], 'is_active' => false, 'sort_order' => 9],
            ['slug' => 'kie-gemini-3-5-flash', 'display_name' => 'Gemini 3.5 Flash', 'kind' => 'text', 'provider_model_id' => 'gemini-3-5-flash', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 2, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 10],
            ['slug' => 'kie-gemini-omni', 'display_name' => 'Gemini Omni', 'kind' => 'video', 'provider_model_id' => 'gemini-omni', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video', 'Video to Video'], 'variants' => 3, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 11],
            ['slug' => 'kie-claude-opus-4-7', 'display_name' => 'Claude Opus 4.7', 'kind' => 'text', 'provider_model_id' => 'claude-opus-4-7', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'Anthropic'], 'is_active' => false, 'sort_order' => 12],
            ['slug' => 'kie-gpt-5-5', 'display_name' => 'GPT-5.5', 'kind' => 'text', 'provider_model_id' => 'gpt-5-5', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'OpenAI'], 'is_active' => false, 'sort_order' => 13],
            ['slug' => 'kie-gpt-image-2', 'display_name' => 'GPT Image 2', 'kind' => 'image', 'provider_model_id' => 'gpt-image-2', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 2, 'upstream' => 'OpenAI'], 'is_active' => false, 'sort_order' => 14],
            ['slug' => 'kie-happyhorse-1-0', 'display_name' => 'HappyHorse-1.0', 'kind' => 'video', 'provider_model_id' => 'happyhorse-1-0 ', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 4, 'upstream' => 'Alibaba'], 'is_active' => false, 'sort_order' => 15],
            ['slug' => 'kie-wan-2-7-video', 'display_name' => 'Wan 2.7 Video', 'kind' => 'video', 'provider_model_id' => 'wan-2-7-video', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video', 'Video to Video', 'Video Editing'], 'variants' => 4, 'upstream' => 'Wan'], 'is_active' => false, 'sort_order' => 16],
            ['slug' => 'kie-seedance-2-0', 'display_name' => 'Seedance 2.0', 'kind' => 'video', 'provider_model_id' => 'seedance-2-0', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video', 'Lip Sync', 'Video Editing', 'Video to Video'], 'variants' => 2, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 17],
            ['slug' => 'kie-wan-2-7-image', 'display_name' => 'Wan2.7 Image', 'kind' => 'image', 'provider_model_id' => 'wan-2-7-image', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 2, 'upstream' => 'Wan'], 'is_active' => false, 'sort_order' => 18],
            ['slug' => 'kie-qwen-image-2', 'display_name' => 'Qwen Image 2.0', 'kind' => 'image', 'provider_model_id' => 'qwen-image-2', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 2, 'upstream' => 'Qwen'], 'is_active' => false, 'sort_order' => 19],
            ['slug' => 'kie-claude-sonnet-4-6', 'display_name' => 'Claude Sonnet 4.6', 'kind' => 'text', 'provider_model_id' => 'claude-sonnet-4-6', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'Anthropic'], 'is_active' => false, 'sort_order' => 20],
            ['slug' => 'kie-claude-opus-4-6', 'display_name' => 'Claude Opus 4.6', 'kind' => 'text', 'provider_model_id' => 'claude-opus-4-6', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'Anthropic'], 'is_active' => false, 'sort_order' => 21],
            ['slug' => 'kie-claude-haiku-4-5', 'display_name' => 'Claude Haiku 4.5', 'kind' => 'text', 'provider_model_id' => 'claude-haiku-4-5', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'Anthropic'], 'is_active' => false, 'sort_order' => 22],
            ['slug' => 'kie-gpt-5-4', 'display_name' => 'GPT-5.4', 'kind' => 'text', 'provider_model_id' => 'gpt-5-4', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'OpenAI'], 'is_active' => false, 'sort_order' => 23],
            ['slug' => 'kie-kling-3-motion-control', 'display_name' => 'Kling 3.0 Motion Control', 'kind' => 'video', 'provider_model_id' => 'kling-3-motion-control', 'capabilities' => ['task_types' => ['Video to Video'], 'variants' => 1, 'upstream' => 'Kling'], 'is_active' => false, 'sort_order' => 24],
            ['slug' => 'kie-codex', 'display_name' => 'OpenAI Codex', 'kind' => 'text', 'provider_model_id' => 'codex', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 5, 'upstream' => 'OpenAI'], 'is_active' => false, 'sort_order' => 25],
            ['slug' => 'kie-gemini-3-1-pro', 'display_name' => 'Gemini 3.1 Pro', 'kind' => 'text', 'provider_model_id' => 'gemini-3-1-pro', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 26],
            ['slug' => 'kie-nano-banana-2', 'display_name' => 'Nano Banana 2', 'kind' => 'image', 'provider_model_id' => 'nano-banana-2', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 1, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 27],
            ['slug' => 'kie-gpt-5-2', 'display_name' => 'GPT-5.2', 'kind' => 'text', 'provider_model_id' => 'gpt-5-2', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'OpenAI'], 'is_active' => false, 'sort_order' => 28],
            ['slug' => 'kie-seedream5-0-lite', 'display_name' => 'Seedream 5.0 Lite', 'kind' => 'image', 'provider_model_id' => 'seedream5-0-lite', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 2, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 29],
            ['slug' => 'kie-kling-3-0', 'display_name' => 'Kling 3.0', 'kind' => 'video', 'provider_model_id' => 'kling-3-0', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video', 'Lip Sync'], 'variants' => 1, 'upstream' => 'Kling'], 'is_active' => false, 'sort_order' => 30],
            ['slug' => 'kie-elevenlabs-text-to-dialogue-v3', 'display_name' => 'ElevenLabs V3', 'kind' => 'audio', 'provider_model_id' => 'elevenlabs/text-to-dialogue-v3', 'capabilities' => ['task_types' => ['Text to Speech'], 'variants' => 1, 'upstream' => 'Elevenlabs'], 'is_active' => false, 'sort_order' => 31],
            ['slug' => 'kie-claude-sonnet-4-5', 'display_name' => 'Claude Sonnet 4.5', 'kind' => 'text', 'provider_model_id' => 'claude-sonnet-4-5', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 2, 'upstream' => 'Anthropic'], 'is_active' => false, 'sort_order' => 32],
            ['slug' => 'kie-claude-opus-4-5', 'display_name' => 'Claude Opus 4.5', 'kind' => 'text', 'provider_model_id' => 'claude-opus-4-5', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 2, 'upstream' => 'Anthropic'], 'is_active' => false, 'sort_order' => 33],
            ['slug' => 'kie-gemini-2-5-flash', 'display_name' => 'Gemini 2.5 Flash', 'kind' => 'text', 'provider_model_id' => 'gemini-2.5-flash', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 34],
            ['slug' => 'kie-gemini-2-5-pro', 'display_name' => 'Gemini 2.5 Pro', 'kind' => 'text', 'provider_model_id' => 'gemini-2.5-pro', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 35],
            ['slug' => 'kie-gemini-3-flash', 'display_name' => 'Gemini 3 Flash', 'kind' => 'text', 'provider_model_id' => 'gemini-3-flash', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 2, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 36],
            ['slug' => 'kie-kling-2-6-motion-control', 'display_name' => 'Kling 2.6 Motion Control', 'kind' => 'video', 'provider_model_id' => 'kling-2.6-motion-control', 'capabilities' => ['task_types' => ['Video to Video'], 'variants' => 1, 'upstream' => 'Kling'], 'is_active' => false, 'sort_order' => 37],
            ['slug' => 'kie-seedance-1-5-pro', 'display_name' => 'Seedance 1.5 Pro', 'kind' => 'video', 'provider_model_id' => 'seedance-1-5-pro', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 1, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 38],
            ['slug' => 'kie-wan-2-6', 'display_name' => 'Wan 2.6', 'kind' => 'video', 'provider_model_id' => 'wan-2-6', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video', 'Video to Video'], 'variants' => 3, 'upstream' => 'Wan'], 'is_active' => false, 'sort_order' => 39],
            ['slug' => 'kie-gpt-image-1-5', 'display_name' => 'gpt-image-1.5', 'kind' => 'image', 'provider_model_id' => 'gpt-image-1.5', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 2, 'upstream' => 'OpenAI'], 'is_active' => false, 'sort_order' => 40],
            ['slug' => 'kie-seedream-4-5', 'display_name' => 'Seedream 4.5', 'kind' => 'image', 'provider_model_id' => 'seedream-4-5', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image', 'Image Editing'], 'variants' => 2, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 41],
            ['slug' => 'kie-kling-2-6', 'display_name' => 'Kling 2.6', 'kind' => 'video', 'provider_model_id' => 'kling-2-6', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 2, 'upstream' => 'Kling'], 'is_active' => false, 'sort_order' => 42],
            ['slug' => 'kie-z-image', 'display_name' => 'Z-Image', 'kind' => 'image', 'provider_model_id' => 'z-image', 'capabilities' => ['task_types' => ['Text to Image'], 'variants' => 2, 'upstream' => 'Qwen'], 'is_active' => false, 'sort_order' => 43],
            ['slug' => 'kie-flux-2', 'display_name' => 'FLUX.2', 'kind' => 'image', 'provider_model_id' => 'flux-2', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 4, 'upstream' => 'Black Forest Labs'], 'is_active' => false, 'sort_order' => 44],
            ['slug' => 'kie-gemini-3-pro', 'display_name' => 'Gemini 3 Pro', 'kind' => 'text', 'provider_model_id' => 'gemini-3-pro', 'capabilities' => ['task_types' => ['Chat'], 'variants' => 1, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 45],
            ['slug' => 'kie-nano-banana-pro', 'display_name' => 'Nano Banana Pro', 'kind' => 'image', 'provider_model_id' => 'nano-banana-pro', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 1, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 46],
            ['slug' => 'kie-seedance-1-0-pro-fast', 'display_name' => 'Seedance 1.0 Pro Fast', 'kind' => 'video', 'provider_model_id' => 'seedance-1-0-pro-fast', 'capabilities' => ['task_types' => ['Image to Video'], 'variants' => 1, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 47],
            ['slug' => 'kie-grok-imagine', 'display_name' => 'Grok Imagine', 'kind' => 'video', 'provider_model_id' => 'grok-imagine', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video', 'Text to Image', 'Image to Image'], 'variants' => 6, 'upstream' => 'Grok'], 'is_active' => false, 'sort_order' => 48],
            ['slug' => 'kie-hailuo-2-3', 'display_name' => 'Hailuo 2.3', 'kind' => 'video', 'provider_model_id' => 'hailuo-2-3', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 2, 'upstream' => 'Hailuo'], 'is_active' => false, 'sort_order' => 49],
            ['slug' => 'kie-veo-3-1', 'display_name' => 'Veo 3.1', 'kind' => 'video', 'provider_model_id' => 'veo-3-1', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 4, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 50],
            ['slug' => 'kie-features-v3-api', 'display_name' => 'Veo 3', 'kind' => 'video', 'provider_model_id' => 'features/v3-api', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 4, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 51],
            ['slug' => 'kie-4o-image-api', 'display_name' => '4o Image', 'kind' => 'image', 'provider_model_id' => '4o-image-api', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 1, 'upstream' => 'OpenAI'], 'is_active' => false, 'sort_order' => 52],
            ['slug' => 'kie-flux-kontext-api', 'display_name' => 'Flux Kontext', 'kind' => 'image', 'provider_model_id' => 'flux-kontext-api', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 1, 'upstream' => 'Black Forest Labs'], 'is_active' => false, 'sort_order' => 53],
            ['slug' => 'kie-topaz-image-upscale', 'display_name' => 'Topaz Image Upscale', 'kind' => 'image', 'provider_model_id' => 'topaz-image-upscale', 'capabilities' => ['task_types' => ['Image to Image'], 'variants' => 1, 'upstream' => 'Topaz'], 'is_active' => false, 'sort_order' => 54],
            ['slug' => 'kie-kling-2-5', 'display_name' => 'Kling 2.5 Turbo', 'kind' => 'video', 'provider_model_id' => 'kling-2-5', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 2, 'upstream' => 'Kling'], 'is_active' => false, 'sort_order' => 55],
            ['slug' => 'kie-wan-2-5', 'display_name' => 'Wan 2.5', 'kind' => 'video', 'provider_model_id' => 'wan-2-5', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 2, 'upstream' => 'Wan'], 'is_active' => false, 'sort_order' => 56],
            ['slug' => 'kie-wan-animate', 'display_name' => 'Wan 2.2 Animate', 'kind' => 'video', 'provider_model_id' => 'wan-animate', 'capabilities' => ['task_types' => ['Image to Video'], 'variants' => 2, 'upstream' => 'Wan'], 'is_active' => false, 'sort_order' => 57],
            ['slug' => 'kie-hailuo-api', 'display_name' => 'Hailuo 02', 'kind' => 'video', 'provider_model_id' => 'hailuo-api', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 4, 'upstream' => 'Hailuo'], 'is_active' => false, 'sort_order' => 58],
            ['slug' => 'kie-topaz-video-upscaler', 'display_name' => 'Topaz Video Upscaler', 'kind' => 'video', 'provider_model_id' => 'topaz-video-upscaler', 'capabilities' => ['task_types' => ['Video to Video'], 'variants' => 1, 'upstream' => 'Topaz'], 'is_active' => false, 'sort_order' => 59],
            ['slug' => 'kie-kling-ai-avatar', 'display_name' => 'Kling AI Avatar 2.0', 'kind' => 'video', 'provider_model_id' => 'kling-ai-avatar', 'capabilities' => ['task_types' => ['Lip Sync'], 'variants' => 2, 'upstream' => 'Kling'], 'is_active' => false, 'sort_order' => 60],
            ['slug' => 'kie-seedream-api', 'display_name' => 'Seedream 4.0', 'kind' => 'image', 'provider_model_id' => 'seedream-api', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 2, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 61],
            ['slug' => 'kie-infinitalk', 'display_name' => 'Infinitalk API-AI lip-sync generator', 'kind' => 'audio', 'provider_model_id' => 'infinitalk', 'capabilities' => ['task_types' => ['Speech to Video', 'Lip Sync'], 'variants' => 1, 'upstream' => 'Other'], 'is_active' => false, 'sort_order' => 62],
            ['slug' => 'kie-recraft-remove-background', 'display_name' => 'Recraft Remove Background', 'kind' => 'image', 'provider_model_id' => 'recraft-remove-background', 'capabilities' => ['task_types' => ['Image to Image'], 'variants' => 1, 'upstream' => 'Recraft'], 'is_active' => false, 'sort_order' => 63],
            ['slug' => 'kie-recraft-crisp-upscale', 'display_name' => 'Recraft Crisp Upscale', 'kind' => 'image', 'provider_model_id' => 'recraft-crisp-upscale', 'capabilities' => ['task_types' => ['Image to Image'], 'variants' => 1, 'upstream' => 'Recraft'], 'is_active' => false, 'sort_order' => 64],
            ['slug' => 'kie-elevenlabs-tts', 'display_name' => 'Elevenlabs Text to Speech', 'kind' => 'audio', 'provider_model_id' => 'elevenlabs-tts', 'capabilities' => ['task_types' => ['Text to Speech'], 'variants' => 2, 'upstream' => 'Elevenlabs'], 'is_active' => false, 'sort_order' => 65],
            ['slug' => 'kie-wan-speech-to-video-turbo', 'display_name' => 'Wan 2.2 A14B Speech to Video Turbo', 'kind' => 'audio', 'provider_model_id' => 'wan-speech-to-video-turbo', 'capabilities' => ['task_types' => ['Speech to Video'], 'variants' => 1, 'upstream' => 'Wan'], 'is_active' => false, 'sort_order' => 66],
            ['slug' => 'kie-seedream', 'display_name' => 'Seedream', 'kind' => 'image', 'provider_model_id' => 'seedream', 'capabilities' => ['task_types' => ['Text to Image'], 'variants' => 1, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 67],
            ['slug' => 'kie-qwen-image', 'display_name' => 'Qwen Image', 'kind' => 'image', 'provider_model_id' => 'qwen-image', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 2, 'upstream' => 'Qwen'], 'is_active' => false, 'sort_order' => 68],
            ['slug' => 'kie-nano-banana', 'display_name' => 'NanoBanana-Gemini 2.5 Flash Image Preview', 'kind' => 'image', 'provider_model_id' => 'nano-banana', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 3, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 69],
            ['slug' => 'kie-runway-api', 'display_name' => 'Runway Video Generation', 'kind' => 'video', 'provider_model_id' => 'runway-api', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 2, 'upstream' => 'Runway'], 'is_active' => false, 'sort_order' => 70],
            ['slug' => 'kie-suno-api', 'display_name' => 'Suno API', 'kind' => 'audio', 'provider_model_id' => 'suno-api', 'capabilities' => ['task_types' => ['Text to Music'], 'variants' => 20, 'upstream' => 'Suno'], 'is_active' => false, 'sort_order' => 71],
            ['slug' => 'kie-qwen-image-edit', 'display_name' => 'Qwen Image Edit', 'kind' => 'image', 'provider_model_id' => 'qwen/image-edit', 'capabilities' => ['task_types' => ['Image to Image'], 'variants' => 1, 'upstream' => 'Qwen'], 'is_active' => false, 'sort_order' => 72],
            ['slug' => 'kie-ideogram-character', 'display_name' => 'Ideogram Character', 'kind' => 'image', 'provider_model_id' => 'ideogram/character', 'capabilities' => ['task_types' => ['Image to Image'], 'variants' => 3, 'upstream' => 'Ideogram'], 'is_active' => false, 'sort_order' => 73],
            ['slug' => 'kie-bytedance-seedance-v1', 'display_name' => 'Seedance V1', 'kind' => 'video', 'provider_model_id' => 'bytedance/seedance-v1', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 5, 'upstream' => 'ByteDance'], 'is_active' => false, 'sort_order' => 74],
            ['slug' => 'kie-kling-v2-1', 'display_name' => 'Kling V2.1', 'kind' => 'video', 'provider_model_id' => 'kling/v2-1', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 4, 'upstream' => 'Kling'], 'is_active' => false, 'sort_order' => 75],
            ['slug' => 'kie-ideogram-v3', 'display_name' => 'Ideogram V3', 'kind' => 'image', 'provider_model_id' => 'ideogram/v3', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 3, 'upstream' => 'Ideogram'], 'is_active' => false, 'sort_order' => 76],
            ['slug' => 'kie-wan-v2-2', 'display_name' => 'Wan V2.2 A14B', 'kind' => 'video', 'provider_model_id' => 'wan/v2-2', 'capabilities' => ['task_types' => ['Text to Video', 'Image to Video'], 'variants' => 2, 'upstream' => 'Wan'], 'is_active' => false, 'sort_order' => 77],
            ['slug' => 'kie-google-imagen4', 'display_name' => 'Imagen 4', 'kind' => 'image', 'provider_model_id' => 'google/imagen4', 'capabilities' => ['task_types' => ['Text to Image', 'Image to Image'], 'variants' => 3, 'upstream' => 'Google'], 'is_active' => false, 'sort_order' => 78],
        ];

        foreach ($models as $m) {
            GenModel::updateOrCreate(
                ['slug' => $m['slug']],
                array_merge($m, [
                    'provider' => 'kie',
                    'cost_credits' => null,   // operador define antes de ativar
                ]),
            );
        }
    }
}
