<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

// Semeia as PERSONAS DE ESTILO na aba Prompts do RedFox (tenant 1) — a família que faltava
// ao lado dos 🎬 Roteirista (texto) e 🎥 Diretor (plano de filmagem). Persona aqui é direção
// VISUAL: entra no prompt de geração de imagem/vídeo (engine: personaDirective) e é o que
// separa "uma foto de uma raposa numa rua" de um plano de cinema.
//
// Origem: biblioteca de excelência do RedFoxCode (14 verticais + 14 grades de cor),
// destilada em instrução de estilo — vocabulário visual concreto (lente, luz, grade,
// textura, composição), não descrição de skill. Referências de cinema são propositais;
// nome de provedor de IA nunca aparece (white-label).
//
// kind: 'image' = still (composição do frame) · 'video' = movimento (câmera, ritmo). As 7
// verticais que servem aos dois têm uma entrada de cada, com o texto adaptado.
//
// Idempotente por (tenant_id, title) — reexecutar não duplica. O cliente pode editar,
// apagar e criar as dele: a aba Prompts é dele.
return new class extends Migration
{
    /** Tenant dono do seed: o primeiro (RedFox id 1 em prod). Null = banco sem tenant → não semeia. */
    private function tenantId(): ?int
    {
        return DB::table('tenants')->orderBy('id')->value('id');
    }

    public function up(): void
    {
        if (! $tenantId = $this->tenantId()) {
            return;
        }
        $now = now();
        $personas = [
            ['kind' => 'image', 'title' => '🎨 Base: Qualidade Visual', 'content' => 'Eleve o registro visual empilhando 2 a 4 sinais de camadas DIFERENTES, nunca vários da mesma: nitidez (8K, ultra-HD, hyper-detailed, tack-sharp focus, every fiber visible), lente (anamorphic 2.39:1, shallow depth of field, f/1.4 bokeh, 35mm full-frame look), luz (motivated lighting, three-point, golden hour, chiaroscuro, Rembrandt), grade (color-graded, teal and orange, Kodak Vision3, LUT applied) e textura (35mm film grain, halation, chromatic aberration, vignetting). Abra pelo instante mais forte — movimento, contraste extremo ou revelação de luz —, nunca por logo ou cartela. Especificidade vence adjetivo: número, técnica nomeada, referência. Jamais misture registros contraditórios.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Bleach Bypass', 'content' => 'Aplique bleach bypass: pretos levantados para cinza escuro (nunca zero puro), brancos comprimidos, saturação global em 10–20%, pele guardando só 15% de calor. 35mm film grain pesado a 150%, brilho metálico duro nas altas, registro documental de filme de guerra, subtom azul-aço frio.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Deserto Saturado (Mad Max)', 'content' => 'Aplique grade de deserto pós-apocalíptico à Fury Road: dia em laranja-areia hiper-saturado a 130%, contraste crocante, altas duramente clipadas, textura suja em evidência. Noite em azul-teal rico de day-for-night com práticas quentes isoladas. Pele curtida em âmbar. Cor agressiva, gráfica, de cartaz.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Fincher (Clínico)', 'content' => 'Aplique a grade sombria de Fincher (Se7en, A Rede Social): viés verde-amarelado nos meios-tons, sombras tingidas de ciano que permanecem detalhadas e nunca esmagadas, paleta dessaturada a 70%, pele levemente pálida. Textura digital impecável, sem grão, nitidez de foco profundo, registro de escritório com mistura fluorescente e tungstênio. Frio, preciso, clínico.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Golden Hour (Luz Natural)', 'content' => 'Aplique grade de naturalismo golden hour: key mel-dourado de sol baixo, sujeitos em contraluz com rim brilhante, lens flares orgânicos e suaves, sombras quentes levantadas, saturação natural em 100%. Emulação Kodak Vision3 250D, halation gentil nas altas, sem dominante artificial — a própria luz é a grade.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Horror Frio', 'content' => 'Aplique grade de horror frio: dominante global azul-esverdeada, saturação drenada a 60%, pele cinza-pálida, sombras densas e invasoras com o detalhe mal retido, uma única prática quente como a única vida no quadro. Negative fill pesado, balanço de branco frio acima de 6500K, imobilidade perturbadora na cor.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Kodachrome Anos 70', 'content' => 'Aplique grade Kodachrome dos anos 1970: altas deslocadas para âmbar quente, vermelhos suaves e alaranjados, verdes puxados para oliva, pretos desbotados com subtom marrom. Grão de filme orgânico pronunciado, leve gate weave, halation ao redor das práticas fortes, suavidade de cópia 35mm. Calor nostálgico de sol batido.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Korean Clean (Comercial)', 'content' => 'Aplique grade limpa de comercial coreano: exposição alta em high-key, brancos neutros a levemente frios, acentos pastéis suaves, sombras levantadas sem grão nenhum, pele luminosa e impecável, bloom gentil nas altas. Registro arejado, otimista, de cosmético premium.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Matrix (Verde Digital)', 'content' => 'Aplique grade verde digital: dominante verde esmeralda (não lima) nos meios-tons, pretos frios esmagados, pele dessaturada puxada para oliva, altas levemente ciano. Baixa variância cromática — o mundo inteiro parece monocromático verde. Registro de luz fluorescente, leve suavidade de CRT nas sombras.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Neon Noir (Night Drive)', 'content' => 'Aplique grade neon noir à Drive e John Wick: pretos limpos e profundos, paleta noturna de magenta, ciano elétrico e âmbar de vapor de sódio vindos só de práticas. Asfalto molhado duplicando cada fonte de luz. Pele iluminada por prática colorida, key magenta e rim ciano. Saturação alta nas luzes, zero nas sombras. Anamorphic flare, gradientes suaves em 10-bit.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Noir P&B Clássico', 'content' => 'Aplique grade preto e branco de noir dos anos 1940: monocromático verdadeiro, key duro de fonte única, chiaroscuro em razão 20:1, padrões de sombra de veneziana e treliça, pretos profundos com altas ricas em prata. Renderização ortocromática da pele, grão de negativo 35mm P&B, feixes de luz na fumaça de cigarro.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Pastel Wes Anderson', 'content' => 'Aplique grade pastel de livro ilustrado à Wes Anderson: paleta curada em rosa-salmão desbotado, amarelo-mostarda, azul-poeira e verde-menta. Luz chapada de baixo contraste, pretos matte levantados, saturação suave e uniforme sem nenhuma cor dominando. Emulação Kodak Portra 400, viés quente, uniformidade pictórica — cada cor no quadro parece dirigida de arte.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Sin City (Cor Isolada)', 'content' => 'Aplique grade de noir gráfico à Sin City: preto e branco de altíssimo contraste, pretos em zero e brancos estourados de forma gráfica, com UM único elemento em spot color (especifique: vestido vermelho, logo lima, uísque âmbar) em saturação total. Dureza de painel de quadrinho, sombras de nanquim, chuva e altas como riscos brancos.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Teal & Orange', 'content' => 'Aplique grade teal and orange de blockbuster: sombras empurradas para teal profundo (matiz 180–200), meios-tons de pele em laranja quente, altas em branco quente limpo. Separação máxima entre sujeito e fundo, contraste médio-alto, saturação em 110% só no par complementar. DaVinci Resolve grade, gamut DCI-P3.'],
            ['kind' => 'image', 'title' => '🎨 Cor: Âmbar Neo-Noir (Blade Runner 2049)', 'content' => 'Aplique a grade de Blade Runner 2049: cena banhada em névoa atmosférica âmbar-laranja monocromática, silhuetas engolidas pelo fog. Acentos de neon ciano e magenta contra o quase-preto. Compromisso tonal extremo — uma única cor domina cada cena. Volumetric light, contraste profundo, limpeza de grande formato à Roger Deakins, grão mínimo.'],
            ['kind' => 'image', 'title' => '🎨 Estilo: Cartoon 2D', 'content' => 'Desenhe como cel animation 2D ocidental e descarte todo vocabulário fotorreal (nada de ray tracing, anamorphic ou \'shot on\'). Declare UM estilo e obedeça: Disney clássico (linha anti-aliased de 2–3px, gradientes quentes, olhos grandes e brilhantes), Warner Bros rubber hose (contorno preto de 4–6px, anatomia impossível, blocos de cor chapados), flat vector (formas sólidas, zero gradiente, paleta de 3 a 5 cores, sem contorno), Ghibli aquarelado (fundos pintados, sangramento nas bordas, verdes sálvia e dourados) ou pixel art de 16 cores. Silhueta legível, pose empurrada além do realismo.'],
            ['kind' => 'image', 'title' => '🎨 Estilo: Cinematográfico', 'content' => 'Componha como still de longa-metragem: lente anamorphic 2.39:1, shallow depth of field entre f/1.4 e f/2.0, foco travado nos olhos, fundo em bokeh. Luz motivada com a fonte visível no quadro — chiaroscuro, Rembrandt ou rim light —, key com temperatura declarada (3000K tungstênio quente, 5600K daylight frio) e fill baixo. Grade teal and orange ou bleach bypass, emulação Kodak Vision3 ou Portra 400, 35mm film grain, halation nos realces. Enquadre 2 ou 3 planos de profundidade, horizonte intencional, proporção letterbox. No registro de Roger Deakins em Blade Runner 2049 ou de Lubezki em O Regresso.'],
            ['kind' => 'image', 'title' => '🎨 Estilo: Gastronomia', 'content' => 'Fotografe para dar fome, não para admirar. Macro 90mm a meio metro — comida em plano aberto lê como foto de mesa, em macro lê como cinema. Backlight é obrigatório: só ele revela vapor, brilho e translucidez, e luz frontal chapada mata o prato. Declare a temperatura conforme a cozinha: 3200K tungstênio para conforto e massas, 5500K daylight para saudável e frutas. Textura em primeiro plano — crosta selada, gordura reluzente, condensação no vidro, cristal de sal. Grade quente e contida; saturação estourada em vermelhos e amarelos denuncia artificialidade. 8K, hyper-detailed, Michelin-quality food cinematography.'],
            ['kind' => 'image', 'title' => '🎨 Estilo: Imobiliário', 'content' => 'Fotografe o espaço como personagem: o comprador compra luz, escala e a sensação de estar ali. Lente honesta de 24 a 35mm — distorção agressiva de 14mm hoje lê como manipulação. Enquadre verticais aprumadas, sight-line atravessando para o cômodo seguinte e o pé-direito dentro do quadro. Luz natural com hora declarada: golden hour de 3000K e sombras longas para fachada e cômodos a oeste, blue hour com tungstênio interno de 2700K aceso para o registro de luxo, 4000K de tarde para uso geral. Encene o vivido — café na bancada, manta no sofá. 8K, Architectural Digest interior polish, saturação contida.'],
            ['kind' => 'image', 'title' => '🎨 Estilo: Moda editorial', 'content' => 'Componha como editorial de moda: a peça é o assunto e a atitude é metade do produto. Especifique tecido, cor, caimento, comprimento, decote, manga e bainha — \'um vestido\' é indirigível. Trate o material pela física dele: seda com specular sheen e dobras fluidas, veludo com absorção anisotrópica, paetê com pontos de luz individuais, jeans com trama visível em macro, linho com a ruga como recurso de design. Luz com soft key mais rim light desenhando a silhueta, direção e Kelvin declarados. Postura dirigida: contrapposto, queixo, olhar direto ou distante. Anamorphic 2.39:1, 35mm grain, Vogue editorial polish, saturação contida.'],
            ['kind' => 'image', 'title' => '🎨 Estilo: Produto (anúncio)', 'content' => 'Componha como anúncio que converte: o produto precisa ser inequívoco no primeiro olhar. Macro na textura — trama do tecido, grão do metal, cremosidade do creme. Luz conforme o material: hard directional com fundo preto para joia e luxo (path-traced reflections, specular que dança nas facetas), clamshell soft de 5500K para beleza (every pore visible, sem suavizar a pele), ray-traced reflections com 5000K neutro para eletrônicos, 3500K quente e lateral para couro e madeira. Fundo limpo: branco infinito, preto seamless, mármore ou gradiente controlado. Rótulo legível. 8K, hyper-detailed, Madison Avenue ad polish.'],
            ['kind' => 'image', 'title' => '🎨 Estilo: Quadrinhos', 'content' => 'Componha como arte sequencial impressa, preservando a identidade do traço, sem vocabulário fotorreal — tinta e trama vencem render. Escolha a escola: super-herói ocidental (contorno de nanquim pesado, sombreado CMYK halftone, primárias de alto contraste, anatomia em escorço, musculatura exagerada), mangá (linha limpa e precisa, screentone em pontos, monocromático com um único acento de cor, olhos expressivos, chiaroscuro dramático), webtoon (cor digital em gradiente suave, cel shading macio, fundos pintados), graphic novel pintada (pincelada visível, paleta contida) ou ligne claire europeia (linha limpa, cor chapada).'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Brand Story', 'content' => 'Filme a marca como documentário emocional: emoção primeiro, informação depois, e o cliente ou fundador é o herói — a marca é apenas o mentor. Mostre em vez de narrar: valores viram comportamento, escolha e sacrifício visíveis. Abra por um gesto humano concreto — mãos calejadas trabalhando, o produto sendo alcançado sem pensar, um momento de conexão, o atrito real antes da solução. Ambientes verdadeiros e imperfeição genuína vencem o polido de banco de imagens. Assinatura final contida: marca, tagline, nota silenciosa. 8K, anamorphic 2.39:1, 35mm grain, Kodak Vision3, luz motivada, feature-film production value.'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Cartoon 2D (animação)', 'content' => 'Anime como cartoon ocidental clássico, com os princípios visíveis: squash-and-stretch (comprime 30–40% no impacto, alonga até 200% na velocidade), antecipação antes de cada ação, follow-through depois dela, trajetória em arco (nunca em linha reta) e exagero em toda pose-chave. Timing casado ao estilo: 24fps snappy com holds de 2 frames nos extremos, 30 ou 60fps de interpolação matemática no flat vector, 12fps de tremor deliberado no stop-motion. Efeitos ancorados no tempo: speed lines, impact frame com flash branco de 1–2 frames, screen shake de 3–5 frames, motion smear, íris fechando no fim.'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Cinematográfico (movimento)', 'content' => 'Dirija como cena de longa: abra pelo impacto — corte seco do macro para o plano geral, breu que explode em luz, olhos que se abrem — e nunca por fade-in. Escolha UM movimento e dê velocidade física: dolly forward a 1.5 ft/s, orbit de 180°, crane subindo de 30 cm a 9 m, Steadicam no ritmo do passo, whip pan de 180° em 0.3s, rack focus em 0.8s. Cadência 24fps theatrical, motion blur por frame, anamorphic flare em cada fonte direta. Luz motivada, grade teal and orange, 35mm film grain. Marque os tempos (\'em 4.2s a câmera entra\'). Registro Deakins, Blade Runner 2049.'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Gancho Viral', 'content' => 'Construa os primeiros 2 segundos como se o resto não existisse. Anatomia: 0 a 0.3s um primeiro frame que registra como \'espera, o quê?\'; 0.3 a 0.8s planta a pergunta; 0.8 a 1.5s a tensão cresce; 1.5 a 2.0s chega o momento de compromisso. Escolha UM mecanismo: escala impossível, física impossível, macro irreconhecível com crash-zoom saindo, revelação inesperada no pull-back, movimento reverso, glitch RGB de 0.2s, speed ramp, congela-e-dispara, explosão de cor sobre o cinza. Nada de logo no gancho: logo sinaliza anúncio e anúncio sinaliza scroll. Precisa funcionar MUDO. 4K crisp detail, energia de handheld.'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Gastronomia (movimento)', 'content' => 'Filme o gesto que dá fome. Escolha UMA money shot e construa tudo em volta dela: fio de molho caindo em slow-motion, queijo esticando, vapor subindo em contraluz, faca rompendo a crosta, gelo caindo no copo com respingo, espuma da cerveja estabilizando, tempero caindo e pousando, maçarico caramelizando o açúcar. Slow-motion de 60fps SÓ no clímax; o resto em velocidade normal. Macro 90mm, backlight sempre, luz motivada por prática visível no quadro. Descreva o áudio implícito — chiado, gorgolejo, estalo da faca — porque ele guia o ritmo. Grade quente e contida, Michelin-quality food cinematography.'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Imobiliário (tour)', 'content' => 'Conduza o tour devagar, entre 1 e 3 ft/s: mais rápido que isso e os cômodos borram. Um movimento por ambiente — Steadicam deslizando no passo humano, crane subindo para revelar o pé-direito, slider passando pela ilha da cozinha, push-in lento até a janela onde a vista preenche o quadro, pull-out saindo do detalhe para a escala. Lidere com o que há de excepcional nos primeiros 5 segundos: a vista, o teto, a luz invadindo o breu. Use ao menos uma transição dia-para-noite. Lente de 24 a 35mm, sem distorção enganosa. Golden hour ou blue hour, Architectural Digest polish, edição contida.'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Moda em movimento', 'content' => 'Filme o que a foto não vende: o tecido em movimento. Planeje o gesto que demonstra o caimento — a barra abrindo no giro, o casaco pesando na passada, cabelo e tecido em slow-motion no vento, a rotação de 360° que revela o corte e a modelagem. Dirija a atitude explicitamente (regal, desafiadora, íntima, vulnerável) e o andar (catwalk lento a 2 ft/s, power-walk urbano a 4 ft/s, deriva editorial). Câmera em Steadicam ou gimbal, 35 a 50mm, f/2.0, tracking casado ao ritmo do passo. Anamorphic 2.39:1, 35mm film grain, Vogue editorial polish, teal and orange contido.'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Motion Design', 'content' => 'Anime software como valor visível: mostre o clique virando resultado, nunca explique por narração. Escolha um estilo e a paleta vem junto — Dark Premium (base navy ou preta, acentos ciano e dourado, 3D isométrico, ray-traced reflections), Clean Minimal (branco, um único acento de marca, muito respiro, 2D chapado), Cyberpunk (preto com magenta, ciano e lima, glitch, tipografia monoespaçada), Glassmorphism (cards translúcidos de vidro fosco sobre gradiente) ou Data-Forward (gráficos dominando, navy com verde e vermelho). Easing matemático, no máximo 4 features com tempos explícitos, UI legível por mais de 1 segundo. Restrição é premium. 4K, Apple-keynote-grade polish.'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Produto (anúncio em vídeo)', 'content' => 'Dirija como comercial de conversão: nos primeiros 2 segundos entregue um gancho que funcione MUDO — queda do produto com motion blur, macro ASMR de textura, antes e depois em corte seco, embalagem abrindo com o produto emergindo na luz direcional, cascata de variantes, mão demonstrando o uso. O produto fica identificável até o terceiro segundo. Depois equilibre 40% isolado e 60% em uso real. Movimento lento vende luxo, rápido vende energia. No máximo 3 textos de 5 a 8 palavras. Últimos 2 segundos com verbo de ação. 8K, gimbal-stabilized, ray-traced reflections, Madison Avenue ad polish.'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Produto 360°', 'content' => 'Mostre o produto por inteiro, com clareza e confiança — a meta é informar, não seduzir. Rotação de 360° em velocidade CONSTANTE, sem acelerar, com ritmo casado ao preço: 12 a 15 segundos por volta em item de luxo, 4 a 6 em item cotidiano. Intercale de 2 a 4 beats de detalhe em macro 100mm que revelem o que a rotação não mostra: acabamento, costura, gravação, grão do material. Luz por categoria — hard key de 5400K com fundo preto para relógio e joia, soft de 3500K com fill por baixo para calçado, 5000K neutro difuso para eletrônico, backlight para vidro fosco. Fundo liso. 8K, every detail visible, path-traced reflections.'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Quadrinhos animados', 'content' => 'Anime a página preservando o traço: a tarefa é preencher a sarjeta, o movimento que o desenhista confiou ao leitor imaginar. Declare a ordem de leitura, porque ela comanda a câmera — LTR ocidental (pans e avanço para a direita), RTL de mangá (tudo invertido), webtoon (scroll vertical contínuo). Escolha a técnica: a borda do quadro rachando e estilhaçando na revelação, speed lines 2D virando motion blur 3D, push-in lento sobre a batida emocional, whip pan entre quadros, splash de nanquim como transição, fundo vivo com personagem parado. Onomatopeia sincronizada ao impacto. Sem vocabulário fotorreal.'],
            ['kind' => 'video', 'title' => '🎥 Estilo: Videoclipe', 'content' => 'Corte na batida — a sincronia é tudo. Mapeie um evento visual para cada evento musical: corte de ângulo no kick, flash de cor no snare, movimento de câmera iniciando no baixo, strobe nos hi-hats, imagem estática no silêncio, aceleração da câmera durante o build e pico de intensidade reservado só para o drop. Escolha UM modo (performance, narrativa ou visualizer) e um gênero, que define o resto: hip-hop pede 35mm grain, prática dura e ouro sobre preto; balada pede anamorphic suave e golden hour; eletrônico pede ray-traced, volumetric fog e neons ciano-magenta; indie pede 16mm e luz natural. O refrão é o pico visual.'],
        ];
        foreach ($personas as $p) {
            DB::table('prompts')->updateOrInsert(
                ['tenant_id' => $tenantId, 'title' => $p['title']],
                ['kind' => $p['kind'], 'content' => $p['content'], 'updated_at' => $now, 'created_at' => $now],
            );
        }
    }

    public function down(): void
    {
        if (! $tenantId = $this->tenantId()) {
            return;
        }
        // Só as personas de estilo (kind preenchido). Os prompts de texto do cliente,
        // que têm kind NULL, não são tocados.
        DB::table('prompts')->where('tenant_id', $tenantId)->whereNotNull('kind')->delete();
    }
};
